name: probando
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  image_picker: ^0.7.5
  splash_screen_view: ^3.0.0
  # shared_preferences: ^2.0.8
  
  # audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  image_path: "imagen/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - imagen/YouTube.jpg
    - imagen/avent.jpg
    - imagen/avent2.png
    - imagen/aventureros.jpg
    - imagen/aventur.jpg
    - imagen/aventureros11.png
    - imagen/BIBLIA_1.jpg
    - imagen/BIBLIA_2.jpg
    - imagen/BIBLIA_3.jpg
    - imagen/BIBLIA_4.jpg
    - imagen/BIBLIA_5.jpg
    - imagen/BIBLIA_6.jpg
    - imagen/PABLO.jpg
    - imagen/ZAQUEO.jpg
    - imagen/ZAQUEO.jpg
    - imagen/DIAS_DE_ORACION.jpg
    - imagen/TRISTE.jpg
    - imagen/PENSATIVO.jpg
    - imagen/MOLESTO.jpg
    - imagen/FELIZ.jpg
    - imagen/pan.jpg
    - imagen/vegetales.jpg
    - imagen/proteina.jpg
    - imagen/lacteos.jpg
    - imagen/ejercicio.jpg
    - imagen/agua.jpg
    - imagen/aire.jpg
    - imagen/descanso.jpg
    - imagen/dientes.jpg
    - imagen/pastor.jpg
    - imagen/escuela.jpg
    - imagen/diacono.jpg
    - imagen/director.jpg
    - imagen/ley1.jpg
    - imagen/ley2.jpg
    - imagen/ley3.jpg
    - imagen/ley4.jpg
    - imagen/ley5.jpg
    - imagen/jacke.jpeg
    - imagen/DIAS_DE_ORACION2.jpg
    - imagen/manos_ayudadoras.jpg
    - imagen/manitos2.jpg
    - imagen/noe.jpg
    - imagen/abraham.png
    - imagen/moises.png
    - imagen/david.png
    - imagen/daniel.png
    - imagen/libros.png
    - imagen/aventurero_z.jpg
    - imagen/musica/himno-de-aventureros-cantado.mp3
    
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

splash_screen_view:


  color: "#ffffff"
  background_image: "assets/YouTube.jpg"

  # Optional parameters are listed below.
  image: "assets/YouTube.jpg"

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  #android: false
  #ios: false
  #web: false

  #android_gravity: center
  #ios_content_mode: center
  #web_image_mode: center

  #fullscreen: true

  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'